version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command:
      mongod --quiet --logpath /dev/null

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    # hostname: zookeeper
    env_file:
      - .env
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    # hostname: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME="localhost"
    env_file:
      - .env
    ports:
      - "9092:9092"
    expose:
      - "9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

